### ISSUE TITLE
Validation error do not reset when field unmounted

### ISSUE THREAD

**Issue by megazoll** [final-form/final-form#101]
### Are you submitting a **bug report** or a **feature request**?

bug report

### What is the current behavior?

Some validation errors do not reset when field unmounted and there is no fields in current form.

Steps to reproduce:

1. Open https://codesandbox.io/s/oj8mrzlwx9
2. Click next
3. Click previous
4. Click next
5. Ensure that error from previous state presented and handleSubmit failed.

### What is the expected behavior?

Error should be removed from state when field unmounted

### Sandbox Link

https://codesandbox.io/s/oj8mrzlwx9

forked from Wizard Form Example

**Comment by erikras** [comment]
Great reporting. Good bug. 👍

**Comment by erikras** [comment]
Published fix in [`v4.5.1`](https://github.com/final-form/final-form/releases/tag/v4.5.1).

**Comment by megazoll** [comment]
@erikras thank you!

**Comment by megazoll** [comment]
@erikras could you please bump new version? Seems like https://github.com/final-form/final-form/commit/d5cc82fe1f48ff3a64b8fa813a66d55bb3c42318 fixes this issue
