### ISSUE TITLE
Error if input name with number

### ISSUE THREAD

**Issue by pvlv** [final-form/final-form#103]
### Are you submitting a **bug report** or a **feature request**?

If input name attr string with number --> `<input name="323412" />`, I have error "Cannot set a numeric property on an object". 

I think this bug happens, because:

```js

// final-form/src/structure/setIn.js

isNaN("4325243")  ===  false // true

isNaN("string_key")  ===  false // false

```

### Sandbox Link

https://codesandbox.io/s/w2po55mw35

**Comment by erikras** [comment]
Due to the way it processes arrays of field, [Final Form does not support numeric field names](https://github.com/final-form/final-form/blob/master/docs/faq.md#why-do-my-numeric-keys-result-in-an-array-structure). You'll have to prefix them with a non-numeric character.
