### ISSUE TITLE
Feature request: Subscription to different fields

### ISSUE THREAD

**Issue by VladimirMilenko** [final-form/final-form#105]
Hey there.
I'm coming with a feature request.

We're facing an issue. We need to trigger updates, based on changes in another field.
As far, as we could see, there is no way to trigger field update based on change in another field.

I think, it's not that hard, to implement partial subscriptions for form values.

**Comment by erikras** [comment]
If you're using React, you could use [this](https://medium.com/@erikras/declarative-form-rules-c5949ea97366). If you're using something other than React, you'll have to implement something similar yourself.

**Comment by erikras** [comment]
Reopen if that approach is insufficient.
