### ISSUE TITLE
[question] does ARRAY_ERROR and FORM_ERROR have to be Symbols?

### ISSUE THREAD

**Issue by Andarist** [final-form/final-form#106]
This is causing me some serious headache when dealing with non es6+ browsers (ie11 😭) and I'm wondering what's the use case for those? Couldnt they easily be replaced with non-symbols?

**Comment by erikras** [comment]
The idea, an I think this is mostly the whole point of symbols, is to avoid namespace collision. They _could_ be a string, but that would make a field name invalid.

Are [polyfills](https://github.com/final-form/final-form#polyfills) not sufficient to alleviate your suffering?

**Comment by Andarist** [comment]
> The idea, and I think this is mostly the whole point of symbols, is to avoid namespace collision. They could be a string, but that would make a field name invalid.

Many libraries use some distinct strings for it - in fact context names in legacy context API even couldnt be symbols so strings were enforce. I understand it's not ideal, because name clash is possible, but I think smth like `@@final-form/ARRAY_ERROR` would be "good enough" and universal.

My use case is pretty niche, but we distribute an installable widget and parts of its code is executed on our customers' website where I cannot just install global polyfill because it might cause numerous unexpected results for them so we avoid it at all costs.

Also this polyfill costs 3kb~ (from what i remember, ive checked it yesterday) which could be avoided.

I understand though that u might not want to migrate off this, as community we probably should start to support more and more es6+ by default, unfortunately on a global market **we** cannot ship it by default, because our customers expect it to work in IE11, some sandboxed windows "smart clients" (which use IE11 engine under the hood) etc - so overally im torn between wanting to support them and also wanting to finally use newer stuff.

Also I've finally debugged my issue to the core and at least I know what happened - after I have polyfilled Symbols (because final-form required this) I've ended up with other issue in `redux` because of that. If you are interested (quick read) you might see my redux PR (with explanation what happened) [here](https://github.com/reactjs/redux/pull/2926).

**Comment by erikras** [comment]
Okay. You've convinced me. 👍

**Comment by Andarist** [comment]
Thanks! 😍

**Comment by erikras** [comment]
Published fix in [`v4.5.1`](https://github.com/final-form/final-form/releases/tag/v4.5.1).
