### ISSUE TITLE
hasValidationErrors is true even though there are no errors

### ISSUE THREAD

**Issue by milesj** [final-form/final-form#121]
### Are you submitting a **bug report** or a **feature request**?

Bug report.

### What is the current behavior?

My form fails to submit because `hasValidationErrors` is true, yet there are no errors in the state.

<img width="712" alt="screen shot 2018-04-25 at 5 28 53 pm" src="https://user-images.githubusercontent.com/143744/39279486-56ff7418-48ae-11e8-8eb7-6565b3a1beb7.png">

Shouldn't the undefined fields NOT be included in the errors object?

### What is the expected behavior?

It is false for no errors.

### What's your environment?

final-form v4.6.1
node 8.9.1
npm 5.6.0

**Comment by erikras** [comment]
Interesting. I guess the `hasValidationErrors` logic needs to crawl the tree of the `errors` object to check for truthy values...

**Comment by tikotzky** [comment]
It seems like errors are set as `undefined` in the error state when you have a field that has validation and also has `validateFields` set to an empty array.

You can see a codesandbox here: https://codesandbox.io/s/p9vqw8x5m7

**Comment by milesj** [comment]
Awesome find! This should unblock us temporarily.

**Comment by Rejjn** [comment]
Any ETA for the release of this fix?

**Comment by erikras** [comment]
Published fix in [`v4.6.2`](https://github.com/final-form/final-form/releases/tag/v4.6.2).

**Comment by erikras** [comment]
Thanks for your work on this, guys. 👍

**Comment by Rejjn** [comment]
Indeed! Thanks!
