### ISSUE TITLE
Pass field metadata to validator

### ISSUE THREAD

**Issue by gustavovnicius** [final-form/final-form#124]
### What is the expected behavior?
The field `validate` signature should be:
`validate?: (value: ?any, allValues: Object, meta: Object) => ?any` since there are a few validations that could benefit from it

Examples:
While composing a `required` and a `unique` validations:

New entity form:
  - if the value is empty, it fails `required` (`{ touched: true, dirty: false }`)
  - if the value is filled and it's not unique, it fails `unique` (`{ touched: true, dirty: true }`)
  - otherwise, valid (`{ touched: true, dirty: true }`)

Now, an edit-like form, with the same validations:
  - if the value is empty, it fails `required` (`{ touched: true, dirty: false }`)
  - if the value is filled and it's not unique, it fails `unique` (`{ touched: true, dirty: true }`)
  - if the value is changed, but it's equal to the original value, do not fail `unique` (`{ touched: true, dirty: false }`) (does not work)
  - otherwise, valid (`{ touched: true, dirty: true }`)

It's kind of a poor example, but my point is: The validations API needs more context, having only the value + a set of values is not enough context for more specific validations, or to decouple validations, fields, components, and forms.

**Comment by erikras** [comment]
Published fix in [`4.10.0`](https://github.com/final-form/final-form/releases/tag/v4.10.0).
