### ISSUE TITLE
Breaking Change in #100 (Accept initialize value for `reset()`)

### ISSUE THREAD

**Issue by jmar777** [final-form/final-form#127]
### Are you submitting a **bug report** or a **feature request**?

This probably leans towards bug report, but at this point it may just warrant some clarification in the documentation. I believe the behavior is currently working as intended, but it was a breaking change during a minor version bump.

### What is the current behavior?

When `reset` is passed directly to a DOM element or a component as an event handler (e.g., `<Button onClick(reset) />`), it will receive the event object from the click event, and that event object is then used as the new `initialValues` for the reset operation.

This effectively means that all of your form values are gone (including previously supplied initial values), and you now just have a `values` object that mirrors all the properties on the `Event` instance.

### What is the expected behavior?

As the `reset()` method is [currently documented](https://github.com/final-form/final-form#reset-initialvalues-object--void), this actually seems like expected behavior. The problem is that this is breaking change for code that previously relied on any arguments that are passed to `reset()` being ignored.

While in general it might be weird to rely on arbitrary arguments being ignored, I would also anticipate that it's not uncommon to pass the `reset` handle directly as an event handler in other codebases as well, so I'm also submitting this just in case anyone else is running into the same problem. For keyword purposes, if you're having the same problem, you might be seeing stuff like this in your console 😁:

> Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the property `nativeEvent` on a released/nullified synthetic event. This is set to null. If you must keep the original synthetic event around, use event.persist().

Anyway, as I suggested above, I'm not sure this qualifies as an actual bug in `final-form`, but I think it does constitute a breaking change, albeit a subtle one, and it may be nice to add a note in the documentation.

I'd be happy to throw some verbiage together if that seems like the correct path forward.

### What's your environment?

* final-form@4.6.1
* node version: v8.5.0
* OS/browser affected: all.

**Comment by Dartv** [comment]
Wow, I've struggled for a couple of hours now because of this! This is definitely a breaking change

**Comment by jannisg** [comment]
Came here with the same question after stepping through the React examples and resetting them seemed to bind the event object to the form values.

In the react examples I was looking at I guess the solution was as simple as `onClick={() => reset(initialValues)}` but I do wonder why one would want to set the event object values as their form values?

Given that I now understand how to workaround this, I would love to understand what setting the event values as your form values would be useful for?

I think @jmar777's approach seems good in that it would then work as I would have intuitively expected it to work :)

**Comment by erikras** [comment]
Good catch, you guys. Investigating...

**Comment by Dartv** [comment]
Ignoring Event will not ultimately fix the problem. I have code that uses `reset` on promise catch, for example. It should at least be documented.

**Comment by erikras** [comment]
That argument and its behavior _is_ [documented](https://github.com/final-form/final-form#reset-initialvalues-object--void). But I've added some [additional warning text](https://github.com/erikras/final-form/compare/repository
).

**Comment by xiety** [comment]
In your "Parse and Format" example 'reset' button doesn't work as expected.
You need to change 'reset' to 'form.reset'

And in many other examples:
https://codesandbox.io/s/10rzowm323
https://codesandbox.io/s/yk1zx56y5j
https://codesandbox.io/s/kl9n295n5
https://codesandbox.io/s/wy7z7q5zx5
https://codesandbox.io/s/2k054qp40
etc.
