### ISSUE TITLE
Promise rejection from onSubmit leaves form in "submitting" state

### ISSUE THREAD

**Issue by dallonf** [final-form/final-form#138]
### Are you submitting a **bug report** or a **feature request**?

I think it's a bug. It's definitely surprising behavior to me.

### What is the current behavior?

https://codesandbox.io/s/4xzr2vwvm4

When `onSubmit` returns a rejected promise, `submitting` stays true on the form state.

### What is the expected behavior?

I would expect the form state to transition to `{ submitting: false, submitFailed: true }`. Not sure what should be done with the rejection after that... maybe re-throw it like it does now? Or add another `onError` callback to the form?

### What's your environment?

Final Form 4.8.2, tested on macOS 10.12.6, Chome 66.0.3359.181.

**Comment by Amandeepsinghghai** [comment]
@dallonf JFYI, [onSubmit](https://github.com/final-form/final-form#onsubmit-values-object-form-formapi-callback-errors-object--void--object--promiseobject--void) react-final-form expects the `promise to resolve` with errors even on failure.

One way that I got around this is -

```
onSubmit = (values, formApi, callback) => {
  // Steps for form submit
}
.then((result) => {
  callback() // Call without arguments to notify final-form of success
  return Promise.resolve(result)
})
.catch((errors) => {
  callback(errors)
  return Promise.reject(errors)
})
```

This way, I am able to chain methods `onSubmit(...).then(() => ....)` as well as let react-final-form do its thing. 
Hope this helps

**Comment by erikras** [comment]
To not leave you all in silence, I spent some time working on this today. The validation bit that @Dema brought up is slightly more complicated than the submission issue. I hope to resolve soon.
