### ISSUE TITLE
Validation if field is not required

### ISSUE THREAD

**Issue by perevezencev** [final-form/final-form#145]
### Are you submitting a **bug report** or a **feature request**?

bug

### What is the current behavior?

When field is not required and have another validators (like `mustBeNumber` and etc)
```
<Field
  allowNull
  name="age"
  validate={composeValidators(mustBeNumber, minValue(18))}
>
  {({ input, meta }) => (
    <div>
      <label>Age</label>
      <input {...input} type="text" placeholder="Age" />
      {meta.error && meta.touched && <span>{meta.error}</span>}
  </div>
)}
</Field>
```
field validation takes place
<img width="561" alt="image" src="https://user-images.githubusercontent.com/5954104/42928304-9f4e1b9c-8b3f-11e8-8473-aa654ea25187.png">

### What is the expected behavior?

But I expected that if `allowNull` is` true`, and the field is not required, the test function will not be called.  Instead, I have to modify the validator function like this:

```
const mustBeNumber = value =>
  value && isNaN(value) ? "Must be a number" : undefined;
```

### Sandbox Link

[![Edit 🏁 React Final Form - Field-Level Validation Example](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/7wq7j91x1q)

### What's your environment?

    "react-final-form": "3.6.5",
    "final-form": "^4.2.0",
    "react": "^16.4.0",

**Comment by erikras** [comment]
Your validation function must account for all possible values. The validation function will be called _on every render_ regardless of the value.

**Comment by perevezencev** [comment]
Well, it's not a bug, but I think it's not convenient to use.
For example, the check function `maxValue(n)` does not check for a "value" and should check that the value is less than `n`.

```
const mustBeNumber = value =>
  isNaN(value) ? "Must be a number" : undefined;
const minValue = min => value =>
  isNaN(value) || value >= min ? undefined : `Should be greater than ${min}`;
const composeValidators = (...validators) => value =>
  validators.reduce((error, validator) => error || validator(value), undefined);

const TextField = ({ required, name, label, validate }) => (
  <Field
    name={name}
    required={required}
    validate={validate}
  >
    {({ input, meta }) => (
      <div>
        <label>{label}</label>
        <input {...input} type="text" placeholder={placeholder} />
        {meta.error && meta.touched && <span>{meta.error}</span>}
      </div>
    )}
  </Field>
);

TextField.defaultProps = {
  required: false,
}

const AgeField = () => (
  <TextField
    name="age"
    label="Age"
    placeholder="Age"
    validate={composeValidators(mustBeNumber, minValue(18))}
  />
);
```
In such a case, `mustBeNumber` and` minValue` only perform their own validation function.
Thank you for attention
