### ISSUE TITLE
Missing dirtyFields type in index.d.ts

### ISSUE THREAD

**Issue by werg27** [final-form/final-form#157]
Hello,

On `4.10.0` I'm trying to use dirtyFields and Typescript shows this error :

> Type '{ initialValues: ArticleFormModel; subscription: { dirtySinceLastSubmit: true; dirtyFields: boole...' is not assignable to type 'IntrinsicAttributes & FormProps & { children?: ReactNode; }'.
  Type '{ initialValues: ArticleFormModel; subscription: { dirtySinceLastSubmit: true; dirtyFields: boole...' is not assignable to type 'FormProps'.
    Types of property 'subscription' are incompatible.
      Type '{ dirtySinceLastSubmit: true; dirtyFields: boolean; }' is not assignable to type 'FormSubscription | undefined'.
        Property 'dirtyFields' does not exist on type 'FormSubscription | undefined'

I think it's missing the type in index.d.ts, is there a reason for that?

Thank you

**Comment by erikras** [comment]
Published fix in [`v4.11.0`](https://github.com/final-form/final-form/releases/tag/v4.11.0).
