### ISSUE TITLE
Form state inspection tool

### ISSUE THREAD

**Issue by IanVS** [final-form/final-form#162]
### Are you submitting a **bug report** or a **feature request**?
Feature Request / Question

I'm trying out this library after having used redux-form for a while, and so far I really like it.  One thing I miss is being able to easily inspect the state of the form in the redux devtools, though.  Is there anything similar for this project?  I looked through the docs and issues, but couldn't find any suggestions on how to inspect the current form state.  Thanks!

**Comment by DerJacques** [comment]
Not sure if it suits your needs, but you can use the React Dev tools to look at the state of the form and all of the fields.

![pasted_image_19_10_2018__15_39](https://user-images.githubusercontent.com/3896442/47221648-454cc300-d3b5-11e8-8f86-c454d279e8bd.png)

**Comment by IanVS** [comment]
That's a good hint, thanks.  It's maybe not _quite_ as nice as the redux devtools, but it's better than nothing!
