### ISSUE TITLE
How to specify a default value when registering a field?

### ISSUE THREAD

**Issue by petegleeson** [final-form/final-form#182]
### Question / **feature request**

Hi there. 👋

I have been looking at using final-form to back a React form package. I have been really impressed so far. We want to expose a `Field` component (similar to what is in react-final-form) with the ability to specify a `defaultValue` on the component.

Our use-case is that people creating a `Field` may not be in charge of rendering the `Form`. Instead they will expose a Field say `UserPickerField` and others can compose that into which ever `Form` makes sense. That's the theory anyway, would be interested to hear if anyone has explored this approach as well.

With this idea, it is awkward to specify the `initialValues` on the `Form` component. Ideally, when a `Field` is mounted it can register itself an initial value. I created this sandbox with the component API we are after. https://codesandbox.io/s/jvn4556plw

The boiled down version of that sandbox is:

```
class Field extends React.Component {
  componentDidMount() {
    // form provided via context
    form.change(props.name, props.defaultValue);
    this.unregister = form.registerField(props.name, ...);
  }

  render() {
    return children(formProps)
  }
}
```

Is this the right idea? Or am I barking up the wrong tree?

**Comment by erikras** [comment]
The different use cases that would never have occurred to me never cease to amaze.

`initialValues` serves two purposes, first to repopulate the form with values, but also for calculating `dirty`/`pristine`. The most common use case / meaning being "these are the values currently in the database for this record". It sounds to me like you would want the field (and form) to be `dirty` on initial render, yes? If not, then it gets more complex (e.g. FF _could_ allow a `setInitial()` API for setting the initial value of a single field, I suppose).

If you don't mind the "change value on mount" idea, like what you implemented, you needn't reimplement `Field` entirely as you have, but you could wrap it pretty easily.

Because this is so rare, and because it could be accomplished so easily by wrapping the existing component, I hesitate to add such functionality to the core library.

**Comment by petegleeson** [comment]
Ahh right I see what you mean about the `dirty`/`pristine` state. Ideally I want those values to be meaningful. I see your point about not wanting to change the core lib for this use-case. I had another think about this today and put together a [codesandbox](https://codesandbox.io/s/lx457oljxz) that illustrates a different solution.

The gist is providing our own "register" function on`Form` via context which the `Field` component calls with it's `defaultValue`.

```js
// Field.js
  componentDidMount() {
    const { name, validation, defaultValue } = this.props;
    const register = this.context;
    register({
      name,
      initialValue: defaultValue,
      register: finalForm => {
        this.unregister = finalForm.registerField(name, /* other config */ );
      }
    });
  }
```

Then when `Form` mounts it iterates through the list of fields and creates the final-form `form` with the defaultValues.

```js
// Form.js
  componentDidMount() {
    const initialValues = this.fields.reduce(
      (initials, field) => ({
        ...initials,
        [field.name]: field.initialValue
      }),
      {}
    );
    this.form = createForm({
      initialValues,
      onSubmit: this.props.onSubmit
    });
    this.fields.forEach(field => {
      field.register(this.form);
    });
  }
```

It relies on the fact that `Form`'s didMount gets called after all `Fields` have called `register`. This is seems reasonable to me? It falls down in the case where `Fields` are added/removed at a later point (a user picks something that adds another field to the form).

Thoughts on this approach? It feels a bit better to me.

https://codesandbox.io/s/lx457oljxz

**Comment by petegleeson** [comment]
We ended up using the mutators feature of the library to do this in a more robust way.

The problem we ran into with the above approach was that `defaultValue` is know always known when the component mounts. There were situations where a textbox was rendered while the current value was being fetched from the server. In this case we would have a render with the `defaultValue` as `""` then the actual value once the network request came back.

I have updated the codesandbox with the new approach using mutators 

https://codesandbox.io/s/lx457oljxz

The tldr is `Form` provides it's own `registerField` function that wraps `finalForm.registerField` and calls a mutator that sets the `value` and `initialValue` when a field is registered.

```
class Form extends React.Component {
  form = createForm({
    initialValues: {},
    onSubmit: this.props.onSubmit,
    mutators: {
      setDefaultValue: ([name, defaultValue], state) => {
        state.formState.initialValues[name] = defaultValue;
        state.formState.values[name] = defaultValue;
      }
    }
  });
  registerField = (name, defaultValue, subscriber, subscription, config) => {
    this.form.pauseValidation();
    const unsubscribe = this.form.registerField(
      name,
      subscriber,
      subscription,
      config
    );
    this.form.mutators.setDefaultValue(name, defaultValue);
    this.form.resumeValidation();
    return unsubscribe;
  };
  render() {
     // ...
  }
}
```

This means we can effectively reset a single field rather than the whole form. I am going to close this issue now. Thanks for the input and great library features @erikras & contributors
