### ISSUE TITLE
Cleanup old/merged branches

### ISSUE THREAD

**Issue by MichaelDeBoey** [final-form/final-form#19]
Just keeping the repo a bit cleaner like in final-form/react-final-form#7 🙂

The following branches are all merged into `master`, so I guess they can be deleted?

- [`arrays`](https://github.com/final-form/final-form/tree/arrays)
- [`blurring-non-active`](https://github.com/final-form/final-form/tree/blurring-non-active)
- [`fix-sync-error-submission-blocking`](https://github.com/final-form/final-form/tree/fix-sync-error-submission-blocking)

Don't know if you're planning on doing something with the [`next`](https://github.com/final-form/final-form/tree/next) branch?

**Comment by erikras** [comment]
Fine, _Mom_, I picked up all my dirty clothes off the floor! 😛 

I was considering doing something with `next`, but am not anymore. Thanks for the nudge.

**Comment by MichaelDeBoey** [comment]
@erikras Good boy! Now you can have an extra cookie after dinner 😛😂

I was thinking about merging everything into the `next` branch. After that merge the `next` into `master`, so `master`'s documentation is always the same as the currently published `npm` version, but it seems you release new features and bug fixes directly after implementing them so...
