### ISSUE TITLE
Is there a way to modify the subscription?

### ISSUE THREAD

**Issue by alirezavalizade** [final-form/final-form#194]
First of all i want to thank you for this amazing library, I have a problem with subscription items (dirty property) and field arrays,  so what is the problem?
I want to check the form is dirty or not, it works very well with normal fields but it is not working with field arrays, [this is a simple example from `react-final-form`](https://codesandbox.io/s/n92014klpp), 
you just need click on `add customer` and then `remove customer`, then you can see nothing changed but the `dirty` property is `true`, I need a way for checking the value of field array and if it's empty array or same initial values modify the subscription properties (dirty).
I know this issue could be related to `react-final-form` but it also could be related to `final-form`.
Thanks

**Comment by k-j-kleist** [comment]
What a coincidence - I was just about to construct a minimal test case for my identical problem with final-form (no react here). But you saved me from that chore.

Additionally, I have observed that changing the value of one of the array fields, does not set the form's dirty property.

**Comment by carl-coolblue** [comment]
@k-j-kleist  You may need to implement `isEqual` on your `FieldArray` to perform a more thorough check as by defaut it's a shallow equal check. Something like:

```javascript
<FieldArray
   name="customers"
   isEqual={(a: any, b: any) => {
            if (a && b) {
              if (a.length !== b.length) {
                return false;
              }
              for (let i = 0; i < a.length; i++) {
                if (a[i] !== b[i]) {
                  return false;
                }
              }
              return true;
            }
            return false;
    }}
...
/>
```
