### ISSUE TITLE
Add info about all possible items in Field's subscription object

### ISSUE THREAD

**Issue by VladShcherbin** [final-form/final-form#20]
Hey

From the [docs](https://github.com/final-form/react-final-form#subscription-fieldsubscription) it's unclear about all the items you can select in Field's `subscription` object.

The mentioned [FieldSubscription](https://github.com/final-form/final-form#fieldsubscription--string-boolean-) type doesn't mention such items as `value` or `touched` props which you'll probably need.

It'll be really useful to have the list with all possible items you can select in Field's `subscription` object.

**Comment by VladShcherbin** [comment]
I'm not using flow so it's possible that it won't show you all possible items too.

**Comment by erikras** [comment]
Thanks! Slopping doc'ing on my part. The Flow values were correct. Just the README was wrong.
