### ISSUE TITLE
Not able to reset errors after form submit

### ISSUE THREAD

**Issue by titenis** [final-form/final-form#207]
Submissions errors example: https://codesandbox.io/s/vql1q4kzv0
- Input any wrong data into fields
- Press log in
- Press reset
- Input correct data
- Fields are shown as incorrect anyway, form `invalid` prop is true

**Comment by gertdreyer** [comment]
Please see https://codesandbox.io/s/github/final-form/react-final-form/tree/master/examples/submission-errors as an updated reference.
