### ISSUE TITLE
Bug: Async validation should prevent submission

### ISSUE THREAD

**Issue by onsta** [final-form/final-form#21]
I will use this example https://codesandbox.io/s/wy7z7q5zx5
only change line 37 to 3000 ms for easier debuging.

1) I type last name Newman and age 27 
2) When I type first name John and within 3000 ms and click submit the form 
3) Then I am able to submit it.

I guess expected behaviour should be for submit to be disabled or wait. Right? I can help to fix it. If we agree that it is a bug.

**Comment by erikras** [comment]
Well, it's _sort of_ a bug. It's unexpected behavior, _but_ the developer does not need to allow submission when `validating === true`. However, it probably should not submit until the async validation passes.

**Comment by onsta** [comment]
Thanks, so I guess it is OK, but the submit button should look like this. <button type="submit" disabled={submitting || validating}>Submit</button> or custom behaviour should be implemented.
