### ISSUE TITLE
Broken link to codesandbox link in the README

### ISSUE THREAD

**Issue by ncphillips** [final-form/final-form#210]
### Are you submitting a **bug report** or a **feature request**?

A broken example in the README.

### What is the current behavior?

The provided link https://8ypq7n41z0.codesandbox.io/ opens a broken sandbox.

<img width="541" alt="image" src="https://user-images.githubusercontent.com/824015/55653604-75521c00-57c5-11e9-83c3-08a6ec90853a.png">

### What is the expected behavior?

Working sandbox

### Sandbox Link

https://8ypq7n41z0.codesandbox.io/ 

### What's your environment?

Firefox

### Other information

<img width="872" alt="image" src="https://user-images.githubusercontent.com/824015/55653652-931f8100-57c5-11e9-9ad4-428f1a8becc9.png">

**Comment by erikras** [comment]
That sandbox is working fine for me. 🤷‍♂️

**Comment by ncphillips** [comment]
Strange. I’ll check again later in a few browsers
