### ISSUE TITLE
Add hasBeenDirtySinceLastSubmit

### ISSUE THREAD

**Issue by ThiefMaster** [final-form/final-form#215]
This would be useful when showing a "success" message in case of `submitSucceeded`. Once the user starts editing fields again it's very confusing if that message stays.

`dirtySinceLastSubmit` kind of works as a criterion to hide it, but then the message shows up again when reverting the change so the form becomes clean again, so being able to check if any fields have been dirty since submitting, even if they became clean again, would be better for this.

**Comment by erikras** [comment]
Wow, that's quite a mouthful. Your use case does make sense, though. 👍

**Comment by ThiefMaster** [comment]
Yeah, not a huge fan of the name. Better suggestions welcome ;)

**Comment by erikras** [comment]
No, the name is perfect. 😄

**Comment by erikras** [comment]
Published fix in [`v4.20.0`](https://github.com/final-form/final-form/releases/tag/v4.20.0).
