### ISSUE TITLE
Linked fields change

### ISSUE THREAD

**Issue by 3jwddgm** [final-form/final-form#23]
Hi! RFF is amazing and super fast. Thanks!

Can i change linked fields? Or calculated fiels?

I need someone like on one field change, different field change or on one field change multiple different fields calculated and change. 

Thanks again!

**Comment by erikras** [comment]
Working on a solution.... 🔨 👷 🚧

**Comment by 3jwddgm** [comment]
NIce, thanks =)

**Comment by MichaelDeBoey** [comment]
This is now possible in [`v1.3.0`](https://github.com/final-form/final-form/releases/tag/v1.3.0) with [🏁 Final Form Calculate](https://github.com/final-form/final-form-calculate) 🙂

**Comment by erikras** [comment]
[Sandbox Example](https://codesandbox.io/s/oq52p6v96y)

**Comment by 3jwddgm** [comment]
Thanks is great =)
