### ISSUE TITLE
prevent closing tab when the form is "touched"

### ISSUE THREAD

**Issue by zsolt-dev** [final-form/final-form#238]
**feature request**

Hi Ericas,

thank for this great library. 

I have an idea for a new feature that is super common and maybe should be included as a listener or something. 

So whenever the form is edited and not saved and you try to close browser window, some warning would pop up that you have unsaved form.

I guess anyone can code it somehow with getting the form status with formspy etc but I this is a very common use case, so maybe this could be a cool plugin to have.

**Comment by erikras** [comment]
Yeah, that's [one of the use cases] the form-wide `dirty`/`pristine` flags are for.

Seems like it should only take two lines to implement, so not worth including in the library. Plus, `final-form` is framework agnostic, i.e. maybe you're not even using the DOM, so it really _can't_ be included.
