### ISSUE TITLE
Surface onSubmit as a first-class argument to createForm()

### ISSUE THREAD

**Issue by kaidjohnson** [final-form/final-form#239]
### Are you submitting a **bug report** or a **feature request**?

Feature Request

### What is the current behavior?

`createForm(config)` hides required property from the API signature:

```
createForm(config); // config.onSubmit is required!
```

### What is the expected behavior?

Surface the required property as a first-class argument (BREAKING CHANGE):

```
createForm(onSubmit, [config]); // config is fully optional
```

### Other information

By surfacing the required arguments directly to an API method, implementations can enforce requirements more easily without having to tightly couple the implementation on top of your library.

For example, if a Vue component were to implement final-form, the component author either has to 
a) surface each property of the form config as a prop (can enforce required prop, but doesn't scale):

```
props: {
  onSubmit: {
    type: Function,
    required: true
  },
  // config is now enforced via implementation rather than the library. library features must be explicitly managed at the implementation, requiring updates to the implementation whenever the library adds/removes features
  validate: { 
    type: Function
    default: () => {}
  },
  validateOnBlur: {
    type: Boolean,
    default: false
  },
  ...etc
}
```

or b) surface the whole config as a single object prop (cannot enforce required prop, but scales with the library):

```
props: {
  config: {
    type: Object,
    required: true // the whole config object is required, but internal props have to be enforced via convention/documentation
  }
}
```

Instead, if final-form surfaces the required property as an argument, the Vue component implementation can enforce the required prop and scale with the library:

```
props: {
  onSubmit: {
    type: Function,
    required: true
  },
  config: Object
}
```

I understand this change would be a somewhat significant breaking change. createForm could support both signatures for a release cycle, with a deprecation notice, or else bump a major version number calling out the change.

Thanks for this library and your consideration about this issue!

**Comment by erikras** [comment]
I do agree that, as the only required config item (and I have received complaints that it shouldn't need to be required, e.g. for auto-save forms), it would've made more sense to separate it out from the "config" object.

However, it _would_ be a breaking change, and the awkwardness of Vue's inability to write a prop definition with only one required key doesn't quite seem like a strong enough argument to tip the scale to making that breaking change, especially with Flow and Typescript's ability to enforce individual required keys.

I do hear your concern, and would be open to hearing, and being persuaded by, more arguments in favor of your position, but I'm not yet convinced of the benefits vs. costs warranting such a change.

**Comment by kaidjohnson** [comment]
No problem, I totally understand. I think making onSubmit optional is probably the cleaner path overall, so consider this a +1 for that initiative.

Thanks for the quick reply!
