### ISSUE TITLE
Distinguish between submitError and validationError on Field level

### ISSUE THREAD

**Issue by Kruspe** [final-form/final-form#283]
### Are you submitting a **bug report** or a **feature request**?

Feature Request

As a User
I want to be able to see if a Field error is a validation error or a submit error
So that I know what I did wrong

**GIVEN** I submit a Form and it contains errors
**WHEN** I start editing the Field
**THEN**  I want the submit error to disappear but any validation errors to still be visible

### What is the current behavior?

There is no way for a specific Field to distinguish between a submitError or a validationError. I want to be able to if the current error for the Field is caused by FieldValidation or FormSubmission

### What is the expected behavior?

Right now I can only check the invalid/valid flag which combines both.

### Other information

This behaviour is already implemented for Forms. We could add the same fields (hasSubmitErrors, hasValidationErrors) to every Field.

**Comment by erikras** [comment]
I think you answered your question of how to do this in the PR.
