### ISSUE TITLE
Error thrown in an async validate function during submit will freeze the whole page

### ISSUE THREAD

**Issue by ThieryMichel** [final-form/final-form#308]
### Are you submitting a **bug report** or a **feature request**?

A bug report

### What is the current behavior?

If form async validate function happen to throw an error during submit, the submit will keep on calling itself, and will freeze the whole page silently.

### What is the expected behavior?

The error bubble up and the submit fail.

### Sandbox Link

Here is [a simple example based on the vanilla js demo](https://codesandbox.io/s/final-form-vanilla-js-demo-0eihc)

### What's your environment?

reproduced on final-form4.18.6 in browser, see the code sandbox link

### Other information

I will try and propose a fix.

**Comment by erikras** [comment]
Fix published in [`v4.18.7`](https://github.com/final-form/final-form/releases/tag/v4.18.7).
