### ISSUE TITLE
IE11 Object.values missing

### ISSUE THREAD

**Issue by eugeneoshepkov** [final-form/final-form#316]
### Are you submitting a **bug report** or a **feature request**?

Bug in IE11

### What is the current behavior?

https://github.com/final-form/final-form/pull/290 introduced usage of `Object.values`, which is not supported by IE11. 

### Proposed solution

Instead of `Object.values(dirtyFieldsSinceLastSubmit).some(value => value)`

Do `Object.keys(dirtyFieldsSinceLastSubmit).some(key => dirtyFieldsSinceLastSubmit[key])`

**Comment by ThiefMaster** [comment]
IE11, really? Why are you using/supporting that? :)

**Comment by eugeneoshepkov** [comment]
Business requirements. Polyfill will add unnecessary page load, increasing parsing & execution time.

**Comment by gertdreyer** [comment]
@ThiefMaster agreed.
Those business requirements are wrong :-)
IE11 is unsupported and adding an IE11 polyfill to support less than 0.6% of users (https://browserslist.dev/) in a widely used library is wasteful and irresponsible.
