### ISSUE TITLE
restart missing from FormApi

### ISSUE THREAD

**Issue by johansigfrids** [final-form/final-form#351]
### Are you submitting a **bug report** or a **feature request**?

Bug report.

### What is the current behavior?

The `FormApi` type definition is missing the new `restart` method. 

### What's your environment?

```
"final-form": "^4.20.0",
"typescript": "^3.8.3",
```

**Comment by erikras** [comment]
Fix released in [`v4.20.2`](https://github.com/final-form/final-form/releases/tag/v4.20.2).
