### ISSUE TITLE
Typescript error using "restart" type

### ISSUE THREAD

**Issue by michalmodrzejewski** [final-form/final-form#352]
### Are you submitting a **bug report** or a **feature request**?

Bug report

### What is the current behavior?

Throws an error `Property 'restart' does not exist on type 'FormApi<AnyObject, Partial<AnyObject>>`

### What is the expected behavior?

Don't throw an error. 

### Code

`onSubmit={async ({ name, age }, { restart }) => {
 await onSubmit({ name, vidyardId });
 setTimeout(() => restart());
  }}`

### What's your environment?

`Final form 4.20 version`

**Comment by erikras** [comment]
Fix released in [`v4.20.2`](https://github.com/final-form/final-form/releases/tag/v4.20.2).
