### ISSUE TITLE
Documentation is half-broken

### ISSUE THREAD

**Issue by dko-slapdash** [final-form/final-form#360]
Hi.

Pages like https://final-form.org/docs/react-final-form/examples/simple?reload=1 or https://final-form.org/docs/react-final-form/api/Form?reload=1 or https://final-form.org/docs/react-final-form/api/Field?reload=1 show Error 404.

![image](https://user-images.githubusercontent.com/46383452/85944086-312aca00-b8e9-11ea-804d-17611d13f87b.png)

![image](https://user-images.githubusercontent.com/46383452/85944091-3720ab00-b8e9-11ea-94b4-c595be153aa4.png)

**Comment by yuriiBorbich** [comment]
+1

**Comment by Xopsy** [comment]
Same issue. To give more information, it looks like in the fourth query parameter always is broken.

For example, this one is working:

https://final-form.org/docs/react-final-form/api

but the sections into of api are not working

https://final-form.org/docs/react-final-form/api/Form?reload=1

**Comment by mhmdAljefri** [comment]
Closing this issue and let us know if you still having this problem :)
