### ISSUE TITLE
reset while onSubmit

### ISSUE THREAD

**Issue by bertho-zero** [final-form/final-form#362]
[Throw error if attempt to reset() when submitting (#229)](https://github.com/final-form/final-form/pull/229)

I think this is a bad approach:

It is common to want to empty the form during / after submission, this should not throw an error and the use of a setTimeout brings (potential) visual glitch and useless re-render.

Rather than an error we could have an internal state which monitors if reset is called during the submit (state.resetWhileSubmitting), then at the end of the submit if state.resetWhileSubmitting is true we can do the necessary.

**Comment by erikras** [comment]
Fix released in [`v4.20.2`](https://github.com/final-form/final-form/releases/tag/v4.20.2).
