### ISSUE TITLE
Object doesn't support property or method 'values' in IE11

### ISSUE THREAD

**Issue by maxdev** [final-form/final-form#371]
Hi,

We use final-form and react-final-form in our project. But seems it not works in IE11.
Browser throws this error in console: `SCRIPT438 Object doesn't support property or method 'values'`

I found, that the issue in this part of final-form code: https://github.com/final-form/final-form/blob/19e66f163976033d74bb22508c7f4a071f9f7ab5/src/FinalForm.js#L548

Is there any solution how to fix it?

**Comment by Shuunen** [comment]
you need the `Object.values` polyfill, here is all the polyfills needed for IE11 : https://polyfill.io/v3/polyfill.min.js?features=Array.from%2CPromise%2CObject.values

**Comment by Shuunen** [comment]
also duplicate of #316

**Comment by gertdreyer** [comment]
IE11 is irrelevant in 2023. If you need/want to support it add your own polyfill as suggested in #316
