### ISSUE TITLE
Financing

### ISSUE THREAD

**Issue by brillout** [final-form/final-form#373]
Hi @erikras,

I'm Romuald from the [Lsos](https://lsos.org/), an organization that develops financial solutions for open source, and we are currently reaching out to projects we like.

We have several solutions depending on your financial goals and we can help with:
- Increasing donations
- Starting/increasing consulting work for your users
- Earning a living from your open source work
- Remunerating and hiring a small engineering team for your open source projects

For example, we can increase donations with the [Lsos Donation Reminder](https://github.com/Lsos/donation-reminder) and the [Lsos Donation Fund](https://lsos.org/fund).

We can also leverage a license clause if you are interested in receiving a substantial remuneration from your open source work. Our license clauses are designed to keep code:
1. Accessible: everything stays free for individuals and small companies &mdash; only large companies pay a small fee.
2. Open: anyone can fork the code and remove the license clause.

Large companies want two things: open source and a way to pay for software. They prefer paying for well-maintained tools rather than using free but unreliable tools. At the end of the day, a license clause can be a win for everyone.

We are focusing on solving the financials of a handful of projects first to then eventually tackle the open source financing problem at large. Let me know if you are interested.

I have read couple of your blog posts and you seem to be quite interested in the whole OSS financing topic; I'm double curious about your thoughts :).

Rom

**Comment by brillout** [comment]
@derjacques Wanna share your motivation to downvote this ticket? I understand this is a tricky topic that needs balancing between open source and financial values.

**Comment by DerJacques** [comment]
@brillout I downvoted the issue, because it felt like low-effort (bordering spam) content to me. It's in no way related to Final Form in particular.

It's the exact same text you posted in various other repos:
https://github.com/rcbyr/keen-slider/issues/48, https://github.com/akiran/react-slick/issues/1862, https://github.com/leandrowd/react-responsive-carousel/issues/489, https://github.com/kidjp85/react-id-swiper/issues/463, etc.

I do understand the importance of financial sustainability, and Final Form already has sponsors that support its development (you can find them in the Readme). It doesn't seem like you issue took that into consideration at all.

**Comment by brillout** [comment]
I'm fairly familiar with Erik's work, and actually one reason I'm reaching out to him is that I know he's interested in the topic.

I am aware that OSS developers get quite a lot of spam already (mostly per email) and I'm sorry to contribute to the spam. I'm thinking of posting to social sites instead of doing cold outreaches, but on the other hand I've a preference of nitpicking who I'm contacting. Getting the right first Lsos users is crucial :).

Sorry and thanks for your reply, I appreciate it.

**Comment by DerJacques** [comment]
@brillout It sounds like your motivation comes from the right place, and I appreciate your honest answer. Still not too happy about the issue, but I understand where you're coming from. Social sites sounds like a good idea, and I think personalising the outreach a bit would help as well. Best of luck!

**Comment by brillout** [comment]
> personalising the outreach a bit would help

That's a good idea. I'll do this if more people show dissatisfaction. Thanks.

And thanks for your kind words. Grüße aus Bayern.

**Comment by erikras** [comment]
We discussed this, and I don't think I'll be transitioning to this model. I do applaud the effort, however.

**Comment by brillout** [comment]
@erikras We are finishing the Lsos Basic implementation and I'll get back to you then. I'll show you how it works - you may be interested... Even if you don't go for it, I'd like to show it to you, it's quite cool and it may change your opinion on OSS financing :)

Honestly, we are developing the best solution out there... if this doesn't nail it I don't know what can :).

@mrpsiho I'm curious why you downvoted this ticket? Note that everything stays 1. open source (i.e. transparent & forkable), and 2. free for hobbyists, small companies, nonprofits, and anyone who cannot afford to pay a fee. I strongly believe financial solutions should preserve these two.

**Comment by mrpsiho** [comment]
@brillout Simply because it is not related to Final Form.

**Comment by brillout** [comment]
@mrpsiho Yes you're right, I'm sorry.

@mrpsiho @DerJacques Btw. I've decided to stop this practice of creating GitHub issues, but I'll be sending emails instead (so far, the vast majority of maintainers didn't mind being cold outreached by the Lsos).
