### ISSUE TITLE
Blur and focus actions

### ISSUE THREAD

**Issue by klis87** [final-form/final-form#38]
**bug report** or **feature request** - hard to tell ;)

### What is the current behavior?
When I use `blur` and `focus` actions, they affect only `active` state of a given field. It would be great, if it could be used also to REALLY focus or blur fields, which sometimes is nice to do programmatically. For instance, lets say you have change password form, and a user sets `password` and `repeatPassword` fields, and clicks enter which submits the form. On submission success, I reset the form. The problem? Repeat password is still focused, and when it is blurred by any user action, it will trigger `this field is required` error message. Here, `blur('repeatPassword')` callled just before `reset` would fix this, but unfortunately it doesn't work for now.

**Comment by erikras** [comment]
For that, you'll have to get a ref to your input and call `.blur()` on the DOM node itself. I'm pretty sure there is no way for this library to do that for you, I'm afraid.

**Comment by klis87** [comment]
@erikras This is what I did, and you are right, this is not really responsibility of this library, and using ref is optimal here.

Btw, thx for this awesome library, the best combination of performance and flexibility in form world :+1:

**Comment by erikras** [comment]
Published `dirtySinceLastCommit` fix in [`v3.1.0`](https://github.com/final-form/final-form/releases/tag/v3.1.0).
