### ISSUE TITLE
"Cannot read property 'entries' of undefined" when renamed field is unregistered

### ISSUE THREAD

**Issue by andrewbents** [final-form/final-form#384]
### Are you submitting a **bug report** or a **feature request**?
bug report

### What is the current behavior?
Un error is thrown when renamed field is unregistered

### What is the expected behavior?
No errors
### What's your environment?
final-form: 4.20.1

### Other information
Looks like it was predicted in https://github.com/final-form/final-form/pull/246#issuecomment-514990153

**Comment by erikras** [comment]
Fix released in [`v4.20.2`](https://github.com/final-form/final-form/releases/tag/v4.20.2).
