### ISSUE TITLE
reset, restart and initialize should take InitialFormValues instead of FormValues

### ISSUE THREAD

**Issue by kkirby** [final-form/final-form#389]
reset, restart and initialize all currently accept the type `FormValues`, though, I would argue that it should be `InitialFormValues`. If you pass a partial object, then the form will be created with only some fields set, which I believe is expected. That means the object passed does not have to be an object containing all of the form values, so it should be `InitialFormValues` instead of `FormValues`.

restart:

https://github.com/final-form/final-form/blob/19e66f163976033d74bb22508c7f4a071f9f7ab5/src/FinalForm.js#L988

reset:

https://github.com/final-form/final-form/blob/19e66f163976033d74bb22508c7f4a071f9f7ab5/src/FinalForm.js#L940

initialize:

https://github.com/final-form/final-form/blob/19e66f163976033d74bb22508c7f4a071f9f7ab5/src/FinalForm.js#L755-L757

**Comment by erikras** [comment]
Published fix in [`v4.20.3`](https://github.com/final-form/final-form/releases/tag/v4.20.3).
