### ISSUE TITLE
Request for new NPM release

### ISSUE THREAD

**Issue by MIKOLAJW197** [final-form/final-form#397]
### What is the current behavior?

Wrong type in FormApi `reset()` method - right now in 4.20.1 version it looks like this:
`reset: (initialValues?: FormValues) => void`

### What is the expected behavior?

You fixed it in #358 and merged it to master - so new version on NPM will fix that. It should look like this:
`reset: (initialValues?: InitialFormValues) => void`

### What's your environment?

final-form: 4.20.1

### Other information

I can project my object on `FormValues` but still when this buf is fixed it will be nice to have new release :)

**Comment by gertdreyer** [comment]
4.20.8 has just been released
