### ISSUE TITLE
Mounting Field with async validator throws error "Cannot read property 'active' of undefined"

### ISSUE THREAD

**Issue by dylanwulf** [final-form/final-form#411]
### Are you submitting a **bug report** or a **feature request**?
Bug report

### What is the current behavior?

If I mount a Field with an async validator, then it throws an error "Cannot read property 'active' of undefined". This issue started in version 4.19.1 and is still present in 4.20.2

### What is the expected behavior?

Should not throw an error

### Sandbox Link

https://codesandbox.io/s/keen-shadow-hppmc?file=/src/index.js

### What's your environment?

OS: Windows 10 64-bit
Node: v14.16.0
final-form: v4.20.1
react-final-form: v6.5.1
react: v16.12.0

**Comment by dylanwulf** [comment]
The error in the issue title only happens in Chrome. If you use Firefox, then the error instead says "field is undefined".

**Comment by stefanprobst** [comment]
this is crashing [here](https://github.com/final-form/final-form/blob/444adcd37ebdd691bc6b20035f47f352ba281fcd/src/FinalForm.js#L507) in `notifyFieldListeners`. @erikras could you comment on if it is enough to just check `if (!field) return` there (it does seem to fix this issue for me)? if yes i'm happy to submit a PR, thanks!
