### ISSUE TITLE
`submitting` is stuck at true when submitting a form with invalid data twice

### ISSUE THREAD

**Issue by adibsaad** [final-form/final-form#412]
### Are you submitting a **bug report** or a **feature request**?

bug report

### What is the current behavior?

If I have a form with a subscription for values, submitting, pristine and submitError, and my onSubmit handler resolves with a promise with the object:

```
{ [FORM_ERROR]: 'some error'}
```

if I then click submit twice with invalid data, `submitting` will be stuck at true and the `submitError` will be null

### What is the expected behavior?

If i keep submitting the form with invalid data, `submitting` should be set back to false and `submitError` should not be set back to null.

### Sandbox Link

Read the observations

https://codesandbox.io/s/ff-submitting-bug-46wju?file=/index.js

**Comment by adibsaad** [comment]
@erikras

**Comment by gertdreyer** [comment]
This is a React-Final-Form specific issue and a duplicate. See linked merge request
