### ISSUE TITLE
How to unregisterField, or at least update the registration?

### ISSUE THREAD

**Issue by msageryd** [final-form/final-form#445]
My app might receive updated field specifications while a form is active.
I'm registering all fields from start, because I need to have access to all fields even if they are not mounted.

When an updated field spec arrives I need to update the field including `fieldState.data` where I keep conditions for some special type of validation.

Here is how I register a field (`field`). I'm not sure if other parts of the registration works, but I'm certain that the `data` part is not updated.

If this particular field got updated conditions, i.e. `conditions[field.fieldName]` I can see this bu console.logging the condition right before registering. If I check `fieldState.data.conditions` after the registration I can see that it holds the old value.

Do I need to unregister a field before registering a field with the same name again?
I tried to unsubscribe from all fields before re-registering, but that didn't help.

```
      return form.registerField(
        field.fieldName,
        (fieldState) => {
          checkConditions({fieldState, form, dispatchCondition});
        },
        {value: true, valid: true, data: true},
        {
          getValidator: () => validators,
          validateFields: field.validateFields,
          data: {conditions: conditions[field.fieldName] ? conditions[field.fieldName] : null},
        }
      );
```

**Comment by gertdreyer** [comment]
@msageryd Can you provide a minimal code Sandbox of what you expect?

**Comment by msageryd** [comment]
@gertdreyer Sorry, I didn't realise that I still had an open issue here. I have migrated to react-hook-form and I don't use final-form anymore.

I will close this issue.
