### ISSUE TITLE
keepDirtyOnReinitialize can't handle undefined value

### ISSUE THREAD

**Issue by mjchang** [final-form/final-form#449]
### Are you submitting a **bug report** or a **feature request**?

Bug report

### What is the current behavior?

If `keepDirtyOnReinitialize` is true, when a field is changed from its initial value to undefined, the initialize logic will set formState.values to undefined which causes the form to crash.

### What is the expected behavior?

`formState.values` should never become undefined. If a field's value is changed to undefined, the key should be removed from `formState.values`.

### What's your environment?

final-form 4.20.6
react-final-form 6.5.8
node 16

**Comment by mjchang** [comment]
@erikras Thanks for merging the fix. Any chance we can get a release?

**Comment by erikras** [comment]
Fix published in [`v4.20.7`](https://github.com/final-form/final-form/releases/tag/v4.20.7).
