### ISSUE TITLE
final-form ^4.20.3 introduced a breaking change for array field names (e.g. choices[]), which worked in v4.20.2

### ISSUE THREAD

**Issue by antonvialibri1** [final-form/final-form#456]
### Are you submitting a **bug report** or a **feature request**?
Bug report

### What is the current behavior?
Starting from `final-form` `v4.20.3` and above, checkboxes with array field names (e.g. `choices[]`) started working unexpectedly, they used to work properly until `v4.20.2`.

#### final-form@4.20.2
When using `final-form@4.20.2`:

```
"final-form": "4.20.2",
"react-final-form": "^6.5.9",
```

The code below works as expected ([v4.20.2 Codesandbox](https://codesandbox.io/s/react-final-form-checkbox-example-v4-20-2-ok-z10vwh)):

```jsx
/* eslint-disable jsx-a11y/accessible-emoji */
import React from "react";
import { render } from "react-dom";
import { Form, useField } from "react-final-form";

const FinalFormCheckbox = ({ name, value, label }) => {
  const renderProps = useField(name, {
    type: "checkbox",
    value
  });

  return (
    <label>
      <input name={name} type="checkbox" value={value} {...renderProps.input} />
      <span>{label}</span>
    </label>
  );
};

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

const onSubmit = async (values) => {
  await sleep(300);
  window.alert(JSON.stringify(values, 0, 2));
};

const App = () => (
  <>
    <h1>React Final Form - Checkbox Example - v4.20.2 - OK </h1>
    <Form
      onSubmit={onSubmit}
      initialValues={{}}
      render={({ handleSubmit, form, submitting, values }) => (
        <form onSubmit={handleSubmit}>
          <div>
            <FinalFormCheckbox
              name="choices[]"
              value="choice_1"
              label="Choice 1"
            />
            <FinalFormCheckbox
              name="choices[]"
              value="choice_2"
              label="Choice 2"
            />
            <FinalFormCheckbox
              name="choices[]"
              value="choice_3"
              label="Choice 3"
            />
          </div>

          <div className="buttons">
            <button type="submit" disabled={submitting}>
              Submit
            </button>
            <button type="button" onClick={form.reset} disabled={submitting}>
              Reset
            </button>
          </div>
          <pre>{JSON.stringify(values, 0, 2)}</pre>
        </form>
      )}
    />
  </>
);

render(<App />, document.getElementById("root"));

```

If you check both `Choice 2` and `Choice 3` you get this shape of data for `values`:

```json
{
  "choices": [
    "choice_2",
    "choice_3"
  ]
}

```

Checkboxes appear to be checked:

![final-form_v4 20 2_checkbox_array_OK](https://user-images.githubusercontent.com/99957910/172352858-2ce05606-73b5-47d1-bd62-be549608a357.png)

#### final-form@^4.20.3, up to v4.20.7
On the other hand, when using `final-form@4.20.3` and above (e.g. `v4.20.7`):

```
"final-form": "^4.20.3",
"react-final-form": "^6.5.9",
```

The same code used above for `v4.20.2` doesn't work as expected in version `4.20.3` and upwards:

- [v4.20.3 Codesandbox - Issue](https://codesandbox.io/s/react-final-form-checkbox-example-v4-20-3-issue-e322g2)
- [v4.20.7 Codesandbox - Issue](https://codesandbox.io/s/react-final-form-checkbox-example-v4-20-7-issue-ohit3x)

If you check  both `Choice 2` and `Choice 3` you get this wrong shape of data for `values`:

```json
{
  "choices": [
    [
      "choice_3"
    ]
  ]
}

```

Also, checkboxes remain in an unchecked state, despite having been checked:

![final-form_v4 20 3_checkbox_array_ISSUE](https://user-images.githubusercontent.com/99957910/172353331-33b51aeb-a491-4b88-bb1c-064cfdf422ff.png)
![final-form_v4 20 7_checkbox_array_ISSUE](https://user-images.githubusercontent.com/99957910/172353341-4b906370-da2f-49ba-9b69-f9a24a13a280.png)

### What is the expected behavior?
`v4.20.3` and above (e.g. `v4.20.7`) should behave consistently as version `v4.20.2`.

### Sandbox Link

- [v4.20.2 Codesandbox - OK](https://codesandbox.io/s/react-final-form-checkbox-example-v4-20-2-ok-z10vwh)
- [v4.20.3 Codesandbox - Issue](https://codesandbox.io/s/react-final-form-checkbox-example-v4-20-3-issue-e322g2)
- [v4.20.7 Codesandbox - Issue](https://codesandbox.io/s/react-final-form-checkbox-example-v4-20-7-issue-ohit3x)

### What's your environment?

Google Chrome

**Comment by erikras** [comment]
Published fix in [`v4.20.8`](https://github.com/final-form/final-form/releases/tag/v4.20.8).
