### ISSUE TITLE
Cannot submit form after returning an error from onSubmit

### ISSUE THREAD

**Issue by sqal** [final-form/final-form#48]
### Are you submitting a **bug report** or a **feature request**?
Bug

### What is the current behavior?

Hey :) please take a look at this example: https://codesandbox.io/s/mq3opx9vo9. 
After submitting a form I return some error from `onSubmit` handler and display it on the page. The problem is that after setting form error(s), form becomes invalid and I cannot send form again. Even calling `form.reset()` (although I do not want to reset fields values to their initial ones)  doesn't help. 

### What is the expected behavior?
Don't mark form as invalid when settings submitError/submitErrors

**Comment by erikras** [comment]
How does a [`dirtySinceLastSubmit` flag](https://github.com/final-form/final-form/issues/4#issuecomment-349580191) sound?

**Comment by sqal** [comment]
hmm but the form is still valid after submitting so why setting invalid flag?

**Comment by erikras** [comment]
So you think that a form with submission errors should still be `valid`?

**Comment by sqal** [comment]
Yes, I think that should be the case. If the form was valid before submitting which means all fields in the form were valid, why suddenly change this flag to invalid? Field values have not changed, both are still valid, so the form should be.

**Comment by VladShcherbin** [comment]
The form shouldn't be valid if there are any errors in it, no matter if they are field or form errors, validation errors or submit ones.

This issue can be solved the way it was discussed in https://github.com/final-form/final-form/issues/4 with currently proposed solutions:

- remove field's submit error on field change, remove form submit error on any field change. I guess, this is how it works in Redux-Form.
- add `dirtySinceLastSubmit` flag, which in this case can be used to trigger button disabled state

**Comment by sqal** [comment]
> remove field's submit error on field change, remove form submit error on any field change. I guess, this is how it works in Redux-Form.

I think that would be ok :)

**Comment by klis87** [comment]
@erikras Do you think `dirtySinceLastSubmit` will be added into the core at some point? I am asking because I really need this to hide error messages from server side on input change.

**Comment by klis87** [comment]
@erikras Awesome, thanks for this!

**Comment by erikras** [comment]
Published `dirtySinceLastCommit` fix in [`v3.1.0`](https://github.com/final-form/final-form/releases/tag/v3.1.0).
