### ISSUE TITLE
FieldArray validation broken in v3.0.0

### ISSUE THREAD

**Issue by ju1ius** [final-form/final-form#49]
### Are you submitting a **bug report** or a **feature request**?

A bug report

### What is the current behavior?

The validation function passed to a field array is never called.
[![Edit Final Form - Issue #49](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/l22oy073wm)

### What is the expected behavior?

The validation function passed to a field array should be called, and work as in v1.

### What's your environment?

```json
{
  "final-form": "3.0.0",
  "final-form-arrays": "1.0.0",
  "react-final-form": "2.0.0",
  "react-final-form-arrays": "1.0.1",
}
```

**Comment by MichaelDeBoey** [comment]
`react-final-form-arrays` has [`final-form-arrays@^1.0.0` as a peerDependency](https://github.com/final-form/react-final-form-arrays/blob/master/package.json#L69), which has [`final-form@^1.2.0` as a peerDependency](https://github.com/final-form/final-form-arrays/blob/master/package.json#L60)

**Comment by ju1ius** [comment]
Ah sorry, my bad, I just blindly assumed codesandbox would respect the version constraints when clicking the update button...
