### ISSUE TITLE
Callback is not passed to onSubmit when using spread operator

### ISSUE THREAD

**Issue by sqal** [final-form/final-form#50]
### Are you submitting a **bug report** or a **feature request**?
Bug

### What is the current behavior?

Example:

```js
const form = createForm({
  onSubmit: (...args) => handleSubmit(...args),
});
```

This way handleSubmit receives only values and form API

### What is the expected behavior?

handleSubmit should also receive the callback as a third parameter.

### Sandbox Link
https://codesandbox.io/s/5k4y9v74rx

**Comment by erikras** [comment]
Interesting find. This is because 🏁FF is checking how many arguments your function takes to know if you are using the callback mechanism or not. If you change the line in your sandbox from...
```jsx
onSubmit: (...args) => this.login(...args),
```
...to...
```jsx
onSubmit: (values, form, callback) => this.login(values, form, callback),
```
...it will work.
