### ISSUE TITLE
React Native support

### ISSUE THREAD

**Issue by cosmith** [final-form/final-form#52]
### Are you submitting a **bug report** or a **feature request**?

Feature request

### What is the current behavior?

Using Final Form on older versions of android with React Native does not work. I get a runtime error because of the use of `for...of` loops and `Symbol` (actually I think these are the same since a Symbol is created during the transpilation of `for...of` by Babel).

### What is the expected behavior?

No runtime error

### Sandbox Link

I'm not sure how to do this... maybe with Expo?

### What's your environment?

```
"final-form": "^3.0.0",
"react-native": "0.48.4",
"react-final-form": "^2.1.0",
```

### Other information

Maybe there is a way to build Final Form with other options to make the end result more compatible? Is there a way to configure Rollup to avoid this issue? I tried using a polyfill but couldn't get it to work.

**Comment by erikras** [comment]
There is only [one `for...of` usage](https://github.com/final-form/final-form/blob/ff88998aa59c2ce9824b9d734e0879a87c841b5a/src/structure/getIn.js#L9) in this library. I'd be fine with replacing it. I'm not so sure about replacing [the `Symbol`](https://github.com/final-form/final-form/blob/67bccbea937e1899c8f054e3364404c0e4180dbe/src/FinalForm.js#L30). I'd be happy to add an additional output file to the build if you can figure out how to tell Rollup/Babel to support older versions of javascript.

**Comment by cosmith** [comment]
Ok I'm going to read up & experiment a bit with Rollup and the lib and let you know!

**Comment by cosmith** [comment]
So after a bit of digging I found a way to make it work on React-Native with 2 polyfills:
Adding this to the top of `index.android.js` fixes the crash.
```js
import "core-js/es6/symbol";
import "core-js/fn/symbol/iterator";
```

So I'm closing this issue! Thanks again.

**Comment by erikras** [comment]
Awesome! Hooray for polyfills! 👍
