### ISSUE TITLE
Explicitly setting an input to dirty

### ISSUE THREAD

**Issue by felixjung** [final-form/final-form#55]
### Are you submitting a **bug report** or a **feature request**?

Feature request

### What is the current behavior?

There does not seem to be an API for setting form fields to dirty.

### What is the expected behavior?

The [FormAPI](https://github.com/final-form/final-form#formapi) currently offers ways to `blur`, `focus`, and `change` fields. However, there is no way to explicitly set a field to dirty. For certain use cases (see example below) this would be very helpful. Alternatively, we could probably achieve the same behavior by manually setting an error on a given field (this is what [Formik allows you to do](https://github.com/jaredpalmer/formik#seterrors-fields--field-string-string---void)).

### Other information

Hi,

We are looking to use React Final Form in our application at work. Evaluating our options and reading the documentation, we couldn't figure out how to address a specific use case.

Say you implement an address lookup with a search field for a post code. Entering the post code will return a partially complete address. One required field is missing.

We populate the form inputs with the address. The house number input field (it's a separate input) remains unchanged. Both the `dirty` and `touched` properties are false and hence our error message for that field won't trigger.

The user would expect the lookup to fill out all inputs and it might be difficult for them to see that one specific input in a larger form is still empty.

Is there a way to explicitly set an individual field of the form to dirty in such a case? Looking at the docs, we couldn't find one.

So far we've considered the following alternatives:

- Focusing on each input when autofilling the form causing them to get touched. Unfortunately, this will case the page to scroll, which we don't want.
- Setting the empty input to some quirky value other than the initial `''` (i.e. undefined). This is really hacky and we'd rather not do it.

I have no code sample as this is a hypothetical question at this point.

Thanks

**Comment by felixjung** [comment]
I'd be happy to help implementing this, if you can share an opinion on the preferred approach for this.

**Comment by felixjung** [comment]
Looking at the implementation, I see that the `pristine`/`dirty` state of a field currently isn't part of the internal form state, but is computed when [publishing the field state](https://github.com/final-form/final-form/blob/master/src/publishFieldState.js#L26) externally(?).

Would it be possible to make the `pristinge`/`dirty` state part of the internal state and to update it when a [field is changed](https://github.com/final-form/final-form/blob/master/src/FinalForm.js#L418-L432):

```javascript
   // ...
  change: (name: string, value: ?any) => {
      const { fields, formState } = state
      if (fields[name] && getIn(formState.values, name) !== value) {
        changeValue(state, name, () => value)
        fields[name].dirty = true
        if (validateOnBlur) {
          notifyFieldListeners()
          notifyFormListeners()
        } else {
          runValidation(name, () => {
            notifyFieldListeners()
            notifyFormListeners()
          })
        }
      }
    },
   // ...
```

This solution of course implies a field will always be dirty after the value has been changed at least once. Would that be desirable?

The solution kind of matches what I'm seeing for the [`focus`](https://github.com/final-form/final-form/blob/master/src/FinalForm.js#L434-L443) and `blur` API functions:

```javascript
    // ...
    focus: (name: string) => {
      const field = state.fields[name]
      if (field && !field.active) {
        state.formState.active = name
        field.active = true
        field.visited = true
        notifyFieldListeners()
        notifyFormListeners()
      }
    },
    // ...
```

What do you think?

**Comment by erikras** [comment]
This is a philosophical issue, I think. People (and presumably form libraries) have different definitions of what "dirty" means.

Yours: "The field has ever been edited"
Mine: "The value of the field is different from the initial value"

Mine requires that `dirty` and `pristine` be "calculated properties". Personally, I rather like the idea of typing into a field, backspacing to undo what you just typed, and having the field (and form) go back to being `pristine`. Aside from that aesthetic difference, my definition has the practical implication that it lets you know if you need to save the record or not.

We could potentially have _another_ flag that was your definition of dirty, but then we run into the hard problem in computer science: naming things. `touched` already has a meaning in Final Form. `changed` or `updated` sort of imply my definition of `dirty` (at least to my brain).

My question to you is, what is the benefit of your definition of `dirty`? What superior UX does it allow you to implement?

**Comment by felixjung** [comment]
Thanks for the response. Honestly, I don't have a real preference for either of the two definitions. I can totally see the elegance in having this be a calculated property.

It's more about solving the problem I described above. How do you trigger validation errors on a field that has not changed at all, but needs to have something like a required error show up to highlight it to the user. In AngularJS, which was the first framework we used in our app, this was no problem because you could just set the pristine/dirty state or validations errors from outside. In React, so far, we've been using a home-grown form solution that had support for this, too. Now that we are looking for an external library for React, we just need to figure out how to cover use cases like the one above.

It is entirely possible that you can do this right now and I'm missing how because of a lack of experience with this library. 😄 And I'm all for not adding a gazillion options to to an elegant library. Maybe an API to set field errors directly until they change (you proposed something similar for handling submission errors in #4) is the way to go here.

**Comment by erikras** [comment]
Oops, I had not read your original description closely enough.

Calling `focus('address'); blur('address');` will not scroll. It will just mark the field as touched in Final Form.

But it sounds like the library could use some way to `setTouched()`. That's all you need, right?

**Comment by felixjung** [comment]
Ah, that's good to know. Exposing `setTouched()` would solve the problem, indeed. Should I try to do that and open a PR?

With regard to your comment on `focus()` and `blur()`. Looking at the code I understand how these methods just affect Final Form's internal field state, which in React Final Form, would then fox instance get exposed to the render prop function. If I wanted to scroll to an input, would I then have to take care of that myself inside, for example, the render prop function?

**Comment by erikras** [comment]
> Should I try to do that and open a PR?

No, you took 4 hours to respond, so I implemented it myself, [as a mutator](https://github.com/final-form/final-form-set-field-touched). 😜 Let me know how it goes. Check out the [Warnings Example](https://github.com/final-form/react-final-form#field-warnings) for an idea of how to use mutators.

> would I then have to take care of that myself...?

Yep.

**Comment by felixjung** [comment]
Whuaaa! Awesome! Thanks. Although I would have loved to contribute. Let's see what happens when we start using this in a month or so. Maybe I get to contribute in the end 😉

**Comment by erikras** [comment]
It's a thing (opening control to field meta data) that's been on my mind for some time. I'm sure you'll make a great contribution some day.

Closing this for now. Reopen if you run into problems.

**Comment by felixjung** [comment]
Thanks.

**Comment by felixjung** [comment]
I realize now, that we probably could have used the data mutator to flag a field in order to force an error message to render.

**Comment by erikras** [comment]
Hehe.. That occurred to me, too, but the `setFieldTouched` needed doing anyway. :-)

**Comment by Ralf8686** [comment]
@erikras but in this case (https://codesandbox.io/s/nrmk7wj5r0), when type somethings to input and after remove all, `pristine` don't equal true. Although I had an empty field initially. It is a bug? Maybe, if initialValues have empty sting, don't need remove them from values. But what do with array, I want push some `{title: ""}`, end after remove title from Input will be `{title: ""}`, not `{}`. As a result, there may be another path without deleting the fields. Now I have a hack - mutator forced null, after change field to empty string.

**Comment by vagusX** [comment]
> Hehe.. That occurred to me, too, but the `setFieldTouched` needed doing anyway. :-)

So now do we have `setFieldTouched` or not?

**Comment by omarish** [comment]
@vagusX yes - see https://github.com/final-form/final-form-set-field-touched

**Comment by omerman** [comment]
For people who came here and actually wants to control weather field will be considered dirty or not,
you can always pass `isEqual` prop to `Field`, for example, I wrapped `Field` component with my custom `select` component, and treated `undefined` as equal to the first option value.
