### ISSUE TITLE
Allow overwriting all form values at once

### ISSUE THREAD

**Issue by klis87** [final-form/final-form#62]
### Are you submitting a **bug report** or a **feature request**?
Feature request

### What is the current behavior?
Currently `FormApi` `change` has a following signature `change: (name: string, value: ?any) => void`.
Is it possible to change all form values at the same time? I tried `change('', formValues)`, but it doesn't work.

### What is the expected behavior?
Passing an empty string to action `change` should overwrite the whole form values.

### What's your environment?
react-final-form: 3.0.2, final-form: 4.0.0

**Comment by erikras** [comment]
How about `initialize()`? Although that has other consequences on `pristine`/`dirty` flags.

Your other option is:
```jsx
form.batch(() => {
  form.change('firstField', newValues.firstField)
  form.change('secondField', newValues.secondField)
  form.change('thirdField', newValues.thirdField)
})
```
Obviously those keys could be looped through, especially if your form values are flat.

Does that help?

**Comment by klis87** [comment]
Thanks, `batch` will help, I will just need to write a small helper for this but this will definitely work!
