### ISSUE TITLE
[flow] Update Form/Field Subscription to be sealed

### ISSUE THREAD

**Issue by rosskevin** [final-form/final-form#67]
### Are you submitting a **bug report** or a **feature request**?
bug

### What is the current behavior?
`FormSubscription | FieldSubscription` is currently unsealed using an indexer. It allows anything.  It should be changed to match typescript definitions fixed in #66.

Discussed here with @erikras https://github.com/final-form/final-form/issues/65#issuecomment-358371679

### What is the expected behavior?
`FormSubscription | FieldSubscription` are sealed types allowing only known keys

**Comment by erikras** [comment]
Published fix in [`v4.1.0`](https://github.com/final-form/final-form/releases/tag/v4.1.0).
