### ISSUE TITLE
Reset form errors?

### ISSUE THREAD

**Issue by zackferrofields** [final-form/final-form#72]
Should `form.reset` clear submit state/errors?
If not how should I clear `submitFailed`, `submitSucceeded`, `submitError` & `submitErrors`?
Perhaps a custom mutator 🤔

https://github.com/final-form/final-form/blob/49a99e46b1d4a511cad624372b5df0ab9a57753d/src/FinalForm.js#L582

**Comment by erikras** [comment]
Yes, it probably should clear those.

**Comment by OsipovDenis** [comment]
Hmm, and how I should apply reset method? I mean, inside the form. When I changed the value in the Field, it must resolve submitError.

**Comment by OsipovDenis** [comment]
I find `dirtySinceLastSubmit` flag, it's awesome ^^

**Comment by erikras** [comment]
Published fix in [`v4.2.1`](https://github.com/final-form/final-form/releases/tag/v4.2.1).
