### ISSUE TITLE
IE11 support - required polyfills

### ISSUE THREAD

**Issue by oliverlaz** [final-form/final-form#79]
### Are you submitting a **bug report** or a **feature request**?
Both :)

### What is the current behavior?
In IE11, ``final-form`` and ``react-final-form`` throw an error because ``Symbol`` isn't available.

```javascript
ReferenceError: 'Symbol' is undefined
./node_modules/final-form/dist/final-form.es.js

 377 | });
 378 | 
 379 | //      
> 380 | var FORM_ERROR = Symbol('form-error');
 381 | var version = '4.2.0';
 382 | 
 383 | var tripleEquals = function tripleEquals(a, b) {
```

### What is the expected behavior?
Obvious solution is to include a polyfill for the ``Symbol`` object. 
However, I think that this should be listed somewhere in the docs. Maybe with a list of additional polyfills that need to be included as well.

### Sandbox Link
Simple form demo can be used for testing - https://codesandbox.io/s/q78r2oqq96

### What's your environment?
- ``final-form@^4.2.0``
- ``react-final-form@^3.1.0``
- ``Windows 7, IE11, node@^8.9.1``

I can help with enhancing the docs, but before I start, it would be good if you can provide me some insights about the library internals, especially the ES2015+ features that aren't supported in older browsers.

**Comment by erikras** [comment]
See https://github.com/final-form/final-form/issues/52#issuecomment-354087347.

**Comment by erikras** [comment]
[Added info in docs](https://github.com/final-form/final-form/commit/ca06bc538d4eb6d37cc5414cdd1ac04b54529529).

**Comment by oliverlaz** [comment]
thank you!
