### ISSUE TITLE
Once there is a submit error, the field never becomes valid

### ISSUE THREAD

**Issue by ForbesLindesay** [final-form/final-form#81]
### Are you submitting a **bug report** or a **feature request**?

Bug report

### What is the current behavior?

I have a form for entering a password. When the form is submitted, I may get an error saying "the password is incorrect" which I return from the onSubmit handler as `{password: 'the password is incorrect'}`, to indicate that the password field is the one that is incorrect.

Unfortunately, after I do this, the form never becomes "valid" again, even after the value has been edited.

### What is the expected behavior?

I thought the error would only be there until I edited the field, at that point, I expected it to return to the valid state again.

### What's your environment?

I'm using react-define-form

**Comment by erikras** [comment]
This should be fixed by the solution proposed here: https://github.com/final-form/final-form/issues/80#issuecomment-367269023 We need to distinguish between submission-invalid and validation-invalid.

**Comment by erikras** [comment]
Published fix in [`v4.5.1`](https://github.com/final-form/final-form/releases/tag/v4.5.1).
