### ISSUE TITLE
Easier way to access registered fields

### ISSUE THREAD

**Issue by milesj** [final-form/final-form#91]
### Are you submitting a **bug report** or a **feature request**?

Feature request.

In my current project, I'm using a custom mutator to set additional field configuration into `field.data.config`, which works great. The problem is there's no easy way with the current API to access registered fields: `form.getRegisteredFields()` just returns the names, `form.getState()` returns form state and not the field objects, `form.registerField()` returns an unsubscriber and not the field object, `form.subscribe()` is form state and not field objects, etc. 

The only approach I've found is to use a mutator like `getFields`, which simply returns `state.fields`, but this seems hacky.

### What is the current behavior?

Field objects are abstracted away.

### What is the expected behavior?

Being able to access fields with something like `form.getFields()`.

### What's your environment?

Final form 4.3.1
Node 8.9.1
NPM 5.6.0

### Other information

N/A

**Comment by erikras** [comment]
How about a `form.getFieldState('fieldName')`?

**Comment by milesj** [comment]
Yup! That sounds like it would work.

**Comment by milesj** [comment]
Awesome thanks!

**Comment by erikras** [comment]
Published fix in [`v4.4.0`](https://github.com/final-form/final-form/releases/tag/v4.4.0).
