### ISSUE TITLE
Accept initialize value for `reset()` 

### ISSUE THREAD

**Issue by quicksnap** [final-form/final-form#98]
### Are you submitting a **bug report** or a **feature request**?

Feature request

### What is the current behavior?

`reset` takes no options and calls `initialize` with initial values.

### What is the expected behavior?

I've found I need to perform this operation:

```js
initialize(mySuperDefaultValues);
reset();
```

It would be great if I could instead call `reset(mySuperDefaultValues)`

In the code, we already call `initialize`: https://github.com/final-form/final-form/blob/master/src/FinalForm.js#L665-L671

We could just pass through an optional argument which defaults to `{}`. Easy peasy PR..

**Comment by erikras** [comment]
Published fix in [`v4.5.1`](https://github.com/final-form/final-form/releases/tag/v4.5.1).
